[package]
name = "two"
version = "0.1.0"
edition = "2021"

[dependencies]
fastedge = { workspace = true}
mime = { workspace = true}
pulldown-cmark = { workspace = true}
url = { workspace = true}
anyhow = { workspace = true}

[lib]
path = "main.rs"
crate-type = ["cdylib"]
